// ===== state =====
let token = localStorage.getItem("token") || null;
let me = null;
let DATA = null;          // dashboard payload
let sortMode = "bid";     // bid | fit
let q = "";
const PAGE_SIZE = 30;
let shown = PAGE_SIZE;    // how many cards currently rendered (for "load more")
let fStage = "", fSector = "", fMatched = false;   // filters
let authMode = "login";
let editingBuyerId = null;

const $ = (id) => document.getElementById(id);
const esc = (s) => (s == null ? "" : String(s)).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const headers = () => token ? { Authorization: `Bearer ${token}` } : {};

async function api(path, opts = {}) {
  const isForm = opts.body instanceof FormData;
  const res = await fetch(path, { ...opts, headers: { ...(opts.body && !isForm ? { "Content-Type": "application/json" } : {}), ...headers(), ...(opts.headers || {}) } });
  if (!res.ok) { let m = res.statusText; try { m = (await res.json()).detail || m; } catch {} const e = new Error(m); e.status = res.status; throw e; }
  return res.status === 204 ? null : res.json();
}
function toast(m) { const t = $("toast"); t.textContent = m; t.classList.add("show"); setTimeout(() => t.classList.remove("show"), 2800); }
function openModal(id) { $(id).classList.add("show"); }
function closeModal(id) { $(id).classList.remove("show"); }

// ===== date helpers (compute days relative to today) =====
const MON = { jan:0,feb:1,mar:2,apr:3,may:4,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11 };
function parseDate(s) {
  if (!s) return null;
  s = String(s).trim();
  let m = s.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})$/);     // DD-MM-YYYY
  if (m) return new Date(+m[3], +m[2] - 1, +m[1]);
  const p = s.split(/\s+/);                                    // DD Mon YYYY
  if (p.length === 3 && MON[p[1].slice(0,3).toLowerCase()] !== undefined) return new Date(+p[2], MON[p[1].slice(0,3).toLowerCase()], +p[0]);
  return null;
}
function today0() { const d = new Date(); d.setHours(0,0,0,0); return d; }
function daysUntil(s) { const d = parseDate(s); return d ? Math.round((d - today0()) / 86400000) : null; }
function bidDays(t) { if (t.is_liq) return null; return daysUntil(t.form_g_by); }
function claimsDays(t) { const d = daysUntil(t.claims_by); return d === null ? t.claims_days : d; }

// ===== auth =====
function renderAuth() {
  const el = $("authRow");
  // Open (completely free) mode: no login chrome, but anyone can pull live data.
  if (DATA && DATA.mode === "open" && !me) {
    $("tierPill").textContent = "OPEN ACCESS";
    $("tierPill").className = "demo-pill";
    if (window.STATIC) {
      // GitHub Pages: data is regenerated by the daily Action, no live backend.
      el.innerHTML = `<span style="color:var(--faint);font-size:12px">Updated daily · public access</span>`;
    } else {
      el.innerHTML = `<span class="desk-login" onclick="openAuth('login')">Desk login</span>
        <button class="refresh" id="refreshBtn" onclick="refreshSource()"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-2.64-6.36"/><path d="M21 3v6h-6"/></svg> Refresh from IBBI</button>`;
    }
    return;
  }
  if (me) {
    const paid = me.tier === "paid" || me.is_admin;
    $("tierPill").textContent = me.is_admin ? "DESK" : paid ? "PREMIUM" : "FREE";
    $("tierPill").className = "demo-pill" + (paid ? "" : " free");
    el.innerHTML = `<span style="color:var(--faint)">${esc(me.email)}</span>
      <button class="btn" onclick="openBuyers()">Client book</button>
      ${me.is_admin ? `<button class="refresh" id="refreshBtn" onclick="refreshSource()"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-2.64-6.36"/><path d="M21 3v6h-6"/></svg> Refresh feed</button>` : ""}
      <button class="btn" onclick="logout()">Log out</button>`;
  } else {
    $("tierPill").textContent = "CONNECTED";
    $("tierPill").className = "demo-pill";
    el.innerHTML = `<button class="btn primary" onclick="openAuth('login')">Log in / Sign up</button>`;
  }
}
function openAuth(mode) { authMode = mode || "login"; applyAuthMode(); $("authErr").textContent = ""; openModal("authModal"); }
function applyAuthMode() {
  const signup = authMode === "signup";
  $("authTitle").textContent = signup ? "Create account" : "Log in";
  $("authSub").textContent = signup ? "Free — browse opportunities instantly" : "Access your client matches";
  $("nameField").style.display = signup ? "flex" : "none";
  $("authToggle").textContent = signup ? "Have an account? Log in" : "New here? Create an account";
}
function toggleAuthMode() { authMode = authMode === "login" ? "signup" : "login"; applyAuthMode(); }
async function submitAuth() {
  const email = $("authEmail").value.trim(), pass = $("authPass").value;
  $("authErr").textContent = "";
  try {
    let data;
    if (authMode === "signup") data = await api("/api/auth/signup", { method: "POST", body: JSON.stringify({ email, password: pass, full_name: $("authName").value }) });
    else data = await api("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ username: email, password: pass }) });
    token = data.access_token; me = data.user; localStorage.setItem("token", token);
    closeModal("authModal"); renderAuth(); toast("Welcome, " + me.email); await load();
  } catch (e) { $("authErr").textContent = e.message; }
}
function logout() { token = null; me = null; localStorage.removeItem("token"); renderAuth(); load(); }
async function refreshMe() { try { me = await api("/api/auth/me"); } catch { me = null; token = null; localStorage.removeItem("token"); } renderAuth(); }

// ===== source pill + stats =====
function setSrc() {
  const el = $("src"), t = $("srctxt");
  if (DATA && DATA.ai_enabled) { el.className = "src live"; t.textContent = "Live feed · AI ranker on · " + DATA.generated; }
  else { el.className = "src snap"; t.textContent = "Rule-based feed · " + (DATA ? DATA.generated : ""); }
}
function renderStats() {
  const opps = DATA.opportunities;
  let soon = 0, liq = 0, clients = 0;
  opps.forEach(o => { const k = stageInfo(o.target).key; if (k === "liq") liq++; else if (k === "soon") soon++; clients += o.match_count; });
  $("stats").innerHTML = `
    <div class="stat teal"><div class="k">Live opportunities</div><div class="v">${opps.length}</div></div>
    <div class="stat amber"><div class="k">Approaching Form G</div><div class="v">${soon}</div></div>
    <div class="stat"><div class="k">Client matches</div><div class="v">${clients} ${DATA.mode==='freemium'&&(DATA.tier==='free'||DATA.tier==='anonymous')?'<small>· locked</small>':''}</div></div>
    <div class="stat red"><div class="k">Liquidations</div><div class="v">${liq}</div></div>`;
}

// ===== deadline helpers =====
function dlClass(d) { if (d === null) return "dl-ok"; if (d < 0) return "dl-closed"; return d <= 5 ? "dl-urgent" : d <= 12 ? "dl-soon" : "dl-ok"; }
function dlText(t) { const d = claimsDays(t); if (d === null) return t.claims_by || "—"; if (d < 0) return "claims closed · " + t.claims_by; return d + "d · claims by " + t.claims_by; }
function stageInfo(t) {
  if (t.is_liq) return { key: "liq", label: "Liquidation · auction route", cls: "st-liq" };
  const d = claimsDays(t);
  if (d !== null && d >= 0) return { key: "early", label: "Early stage · claims open", cls: "st-early" };
  return { key: "soon", label: "Form G approaching", cls: "st-soon" };
}

// ===== financial-data research switches =====
// Listed companies -> Screener (ratios). Private -> VCCEdge + Tofler (free filings).
function researchLinks(t) {
  const name = t.name || "";
  const q = encodeURIComponent(name);
  const isPrivate = /\bPVT\b|\bPRIVATE\b/i.test(name);
  const links = [];
  if (isPrivate) {
    links.push({ cls: "tof", label: "Tofler", typ: "private", url: `https://www.tofler.in/search?query=${q}` });
    links.push({ cls: "", label: "VCCEdge", typ: "sub", url: `https://www.vccedge.com/` });
  } else {
    links.push({ cls: "scr", label: "Screener", typ: "listed", url: `https://www.screener.in/full-text-search/?q=${q}` });
    links.push({ cls: "tof", label: "Tofler", typ: "filings", url: `https://www.tofler.in/search?query=${q}` });
  }
  return `<div class="reslinks"><span class="reslabel">Financials</span>${links.map(l =>
    `<a class="reslink ${l.cls}" href="${l.url}" target="_blank" rel="noopener" title="Open ${esc(name)} on ${l.label}">${l.label} <span class="typ">${l.typ}</span><span class="ar">↗</span></a>`
  ).join("")}</div>`;
}

// ===== panels =====
function formgPanel(t) {
  if (t.is_liq) return `<div class="panel"><h4><span class="ic"></span>Process &amp; entry route</h4>
    <div class="prow"><span class="lab">Stage</span><span class="val">Liquidation</span></div>
    <div class="prow"><span class="lab">Acquisition route</span><span class="val">Asset sale via e-auction</span></div>
    <div class="prow"><span class="lab">Auction notice</span><span class="val"><span class="tag t-pending">AWAITED · ALERTED</span></span></div>
    <div class="prow"><span class="lab">Liquidator</span><span class="val">${esc(t.resolution_professional)}</span></div></div>`;
  return `<div class="panel"><h4><span class="ic"></span>Form G / process tracker</h4>
    <div class="prow"><span class="lab">Stage</span><span class="val">CIRP admitted · ${esc(t.admit)}</span></div>
    <div class="prow"><span class="lab">Form G (your entry)</span><span class="val"><span class="tag t-pending">PENDING</span></span></div>
    <div class="prow"><span class="lab">Expected by (≈75d)</span><span class="val">~ ${esc(t.form_g_by || '—')}</span></div>
    <div class="prow"><span class="lab">On publish</span><span class="val">${(BRANDS[(DATA&&DATA.brand)||'kcm']||BRANDS.kcm).name} alerts you</span></div>
    <div class="prow"><span class="lab">EoI contact</span><span class="val">${esc(t.resolution_professional)}</span></div></div>`;
}
function finPanel(t) {
  const d = claimsDays(t);
  const cs = (d !== null && d < 0) ? "collating (window closed)" : "collating (window open)";
  return `<div class="panel"><h4><span class="ic"></span>Financial snapshot</h4>
    <div class="prow"><span class="lab">Lead applicant / creditor</span><span class="val">${esc(t.applicant || '—')}</span></div>
    <div class="prow"><span class="lab">Total admitted claims</span><span class="val"><span class="tag t-live">${cs}</span></span></div>
    <div class="prow"><span class="lab">Revenue · net worth · debt</span><span class="val"><span class="tag t-sub">ON SUBSCRIPTION · MCA</span></span></div>
    <div class="prow"><span class="lab">Liquidation vs GC value</span><span class="val"><span class="tag t-locked">IN IM · ON EoI</span></span></div></div>`;
}

// ===== matches =====
function matchRow(m) {
  const cls = m.conf_class === "g-ok" ? "prime" : m.conf_class === "g-warn" ? "mixed" : "cold";
  const fit = (m.synergy_type || "").toLowerCase();
  const fitLabel = { backward: "Backward", forward: "Forward", horizontal: "Horizontal" }[fit] || "Adjacency";
  const trunc = (m.rationale || "").length >= 235 ? "…" : "";
  return `<div class="match ${cls}">
    <div class="m-left">
      <div class="m-buyer">${esc(m.client)}</div>
      <span class="fit ${fit}">${fitLabel}</span>
      <div class="score"><div class="bar"><i style="width:${m.bar_w || Math.min(100, m.score * 2.5)}%"></i></div><b>${Math.round(m.score)}</b></div>
      <div class="matchedon"><b>matched on:</b> ${esc(m.matched_keywords || '—')}</div>
    </div>
    <div class="m-right">
      <div class="rat">${esc(m.rationale)}${trunc}</div>
      <div class="gates">
        <span class="gate ${m.na_class || 'g-warn'}">29A <b>${esc(m.eligibility_29a || 'Verify')}</b></span>
        <span class="gate g-ok">KCM reach <b>${esc(m.reach || 'Verify')}</b></span>
        <span class="gate ${m.conf_class || 'g-warn'}">Data <b>${esc(m.confidence || 'MEDIUM')}</b></span>
      </div>
    </div>
  </div>`;
}
function lockedPanel(o) {
  return `<div class="locked">
    <div class="lk">
      <div class="lkico"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg></div>
      <div><div class="lkt">${o.match_count} matched client${o.match_count === 1 ? '' : 's'} in the book</div>
      <div class="lks">Synergy fit, 29A eligibility, KCM reach &amp; data confidence — premium.</div></div>
    </div>
    <button class="btn amber" onclick="${me ? 'openUpgrade()' : "openAuth('signup')"}">${me ? 'Unlock matches' : 'Sign up to unlock'}</button>
  </div>`;
}

// ===== engage CTA (lead funnel) =====
function engageBar(t) {
  const email = (DATA && DATA.contact_email) || "";
  if (!email) return "";
  const subj = encodeURIComponent(`KCM IBC Finder — interest in ${t.name}`);
  const body = encodeURIComponent(
    `Hello KCM team,\n\nWe are interested in exploring the distressed asset "${t.name}"`
    + ` (${t.stage_label || t.status}${t.admit ? ", admitted " + t.admit : ""}).\n`
    + `Please advise on acquisition / structuring and feasibility.\n\nRegards,`);
  return `<div class="engage"><span class="engage-q">Considering this asset for acquisition?</span>`
    + `<a class="engage-btn" href="mailto:${email}?subject=${subj}&body=${body}">Engage KCM on this asset →</a></div>`;
}

// ===== render =====
function render() {
  if (!DATA) return;
  let rows = DATA.opportunities.slice();
  if (q) { const k = q.toLowerCase(); rows = rows.filter(o => (o.target.name + " " + o.target.sector + " " + o.target.applicant).toLowerCase().includes(k)); }
  if (fStage) rows = rows.filter(o => fStage === "liq" ? o.target.is_liq : !o.target.is_liq);
  if (fSector) rows = rows.filter(o => (o.target.sector || "").toLowerCase().includes(fSector.toLowerCase()));
  if (fMatched) rows = rows.filter(o => o.match_count > 0);
  $("fClear").style.display = (fStage || fSector || fMatched) ? "inline-block" : "none";
  if (sortMode === "bid") rows.sort((a, b) => { const va = bidDays(a.target) ?? -1, vb = bidDays(b.target) ?? -1; return vb - va; });
  else rows.sort((a, b) => { const sa = a.matches[0]?.score ?? a.match_count ?? 0, sb = b.matches[0]?.score ?? b.match_count ?? 0; return sb - sa; });

  let soon = 0, early = 0, liq = 0;
  rows.forEach(o => { const k = stageInfo(o.target).key; if (k === "soon") soon++; else if (k === "early") early++; else liq++; });
  const visible = rows.slice(0, shown);
  $("hiddenNote").innerHTML = `Showing ${visible.length} of ${rows.length} · sorted by <b>${sortMode === "bid" ? "days to bid (most→least)" : "best fit"}</b> &nbsp;·&nbsp; <b style="color:var(--amber)">${soon} approaching Form G</b> · ${early} early-stage · ${liq} liquidation`;

  if (!rows.length) { $("list").innerHTML = `<div class="opp" style="padding:30px;text-align:center;color:var(--faint)">No opportunities match.</div>`; return; }

  $("list").innerHTML = visible.map((o, i) => {
    const t = o.target, si = stageInfo(t), bd = bidDays(t);
    const matchesHtml = o.locked
      ? lockedPanel(o)
      : (o.matches.length
        ? `<div class="mlabel">Matched clients · ${o.matches.length} (ranked by rule-based fit)</div>${o.matches.map(matchRow).join("")}`
        : `<div class="mlabel">Matched clients</div><div class="locked" style="border-style:solid;background:var(--grey-soft);border-color:var(--line2)"><div class="lks">No client in the book matches this sector yet.</div></div>`);
    return `<div class="opp" style="animation-delay:${i * 55}ms">
      <div class="opp-head">
        <div class="opp-id">
          <div class="opp-name">${esc(t.name)} <span class="stagechip ${si.cls}">${si.label}${t.is_liq ? "" : (bd !== null ? " · ~" + bd + "d to bid" : "")}</span></div>
          <div class="vchain"><b>Sector ·</b> ${esc(t.sector || "inferred from filing")}</div>
          <div class="applicant">Applicant: ${esc(t.applicant || "—")}</div>
          ${researchLinks(t)}
        </div>
        <div class="opp-tags">
          <span class="stage ${t.stage_class}">${esc(t.stage_label || t.status)}</span>
          <span class="deadline">Claims <span class="dl-pill ${dlClass(claimsDays(t))}">${dlText(t)}</span></span>
          <a class="formg-btn" href="${esc(t.source_url || 'https://www.ibbi.gov.in/en/public-announcement')}" target="_blank" rel="noopener">Find on IBBI ↗</a>
          <span class="rp">${esc(t.resolution_professional)}</span>
        </div>
      </div>
      <div class="panels">${formgPanel(t)}${finPanel(t)}</div>
      <div class="matches">${matchesHtml}</div>
      ${engageBar(t)}
    </div>`;
  }).join("");

  const moreEl = $("loadMore");
  if (rows.length > shown) {
    moreEl.style.display = "block";
    moreEl.querySelector("button").textContent = `Load more · ${rows.length - shown} remaining`;
  } else {
    moreEl.style.display = "none";
  }
}
function loadMore() { shown += PAGE_SIZE; render(); }
function resetPaging() { shown = PAGE_SIZE; }

// ===== upgrade / paywall =====
async function openUpgrade() {
  const plan = await api("/api/billing/plan");
  $("upPrice").textContent = `₹${plan.price_inr.toLocaleString("en-IN")} / month`;
  $("upFeat").innerHTML = `
    <div class="free"><h5>Free</h5><ul>${plan.features_free.map(f => `<li>${esc(f)}</li>`).join("")}</ul></div>
    <div class="paid"><h5>Premium ★</h5><ul>${plan.features_paid.map(f => `<li>${esc(f)}</li>`).join("")}</ul></div>`;
  $("upBtn").textContent = plan.payments_enabled ? "Subscribe with Razorpay" : "Unlock (demo)";
  $("upNote").textContent = plan.payments_enabled ? "Secure payment via Razorpay." : "Payments not configured yet — unlocks premium for testing.";
  openModal("upModal");
}
async function upgrade() {
  try {
    const co = await api("/api/billing/checkout", { method: "POST" });
    if (co.mode === "razorpay") return razorpayPay(co);
    await api("/api/billing/confirm", { method: "POST", body: JSON.stringify({}) });
    await refreshMe(); closeModal("upModal"); toast("Premium unlocked!"); await load();
  } catch (e) { if (e.status === 401) { closeModal("upModal"); openAuth("login"); } else toast(e.message); }
}
function razorpayPay(co) {
  const opts = { key: co.razorpay_key_id, amount: co.amount_inr * 100, currency: "INR", name: (BRANDS[(DATA&&DATA.brand)||'kcm']||BRANDS.kcm).name, description: "Premium subscription", order_id: co.order_id,
    handler: async (r) => { await api("/api/billing/confirm", { method: "POST", body: JSON.stringify({ order_id: r.razorpay_order_id, payment_id: r.razorpay_payment_id, signature: r.razorpay_signature }) }); await refreshMe(); closeModal("upModal"); toast("Premium unlocked!"); await load(); } };
  const s = document.createElement("script"); s.src = "https://checkout.razorpay.com/v1/checkout.js"; s.onload = () => new Razorpay(opts).open(); document.body.appendChild(s);
}

// ===== client book (buyers) =====
async function openBuyers() {
  $("recomputeBtn").style.display = me && me.is_admin ? "inline-flex" : "none";
  await renderBuyers(); openModal("buyersModal");
}
async function renderBuyers() {
  const rows = await api("/api/buyers");
  $("buyerList").innerHTML = rows.length ? rows.map(b => `<div class="blrow"><div><div class="bn">${esc(b.name)}</div><div class="bs">${esc(b.sector || "—")}${b.surplus_cash_inr_cr ? " · ₹" + b.surplus_cash_inr_cr + " cr" : ""}</div></div><div style="display:flex;gap:10px"><button class="mini" onclick='editBuyer(${b.id})'>edit</button><button class="mini del" onclick='delBuyer(${b.id})'>delete</button></div></div>`).join("") : `<div class="bs" style="padding:8px">No clients yet. Add one or import a spreadsheet.</div>`;
}
function clearBuyerForm() { ["bName","bSector","bProducts","bNeeds","bCustomers","bThesis","bCash"].forEach(i => $(i).value = ""); $("bErr").textContent = ""; }
function openBuyerForm() { editingBuyerId = null; $("bfTitle").textContent = "Add client"; clearBuyerForm(); openModal("buyerFormModal"); }
async function editBuyer(id) {
  const rows = await api("/api/buyers"); const b = rows.find(x => x.id === id); if (!b) return;
  editingBuyerId = id; $("bfTitle").textContent = "Edit client";
  $("bName").value = b.name; $("bSector").value = b.sector; $("bProducts").value = b.products; $("bNeeds").value = b.raw_materials_needed; $("bCustomers").value = b.customers_served; $("bThesis").value = b.acquisition_thesis; $("bCash").value = b.surplus_cash_inr_cr;
  openModal("buyerFormModal");
}
async function saveBuyer() {
  const body = { name: $("bName").value.trim(), sector: $("bSector").value, products: $("bProducts").value, raw_materials_needed: $("bNeeds").value, customers_served: $("bCustomers").value, acquisition_thesis: $("bThesis").value, surplus_cash_inr_cr: parseFloat($("bCash").value) || 0 };
  if (!body.name) { $("bErr").textContent = "Name is required."; return; }
  try { if (editingBuyerId) await api("/api/buyers/" + editingBuyerId, { method: "PUT", body: JSON.stringify(body) }); else await api("/api/buyers", { method: "POST", body: JSON.stringify(body) }); closeModal("buyerFormModal"); renderBuyers(); toast("Saved"); }
  catch (e) { $("bErr").textContent = e.message; }
}
async function delBuyer(id) { if (!confirm("Delete this client?")) return; await api("/api/buyers/" + id, { method: "DELETE" }); renderBuyers(); toast("Deleted"); }
async function importBuyers(input) { if (!input.files.length) return; const fd = new FormData(); fd.append("file", input.files[0]); try { const r = await api("/api/buyers/import", { method: "POST", body: fd }); toast(`Imported ${r.imported} client(s)`); renderBuyers(); } catch (e) { toast("Import failed: " + e.message); } input.value = ""; }
async function recompute() { toast("Recomputing matches…"); try { const r = await api("/api/match/run-all", { method: "POST" }); toast(`Matched ${r.buyers} clients × ${r.targets} targets`); await load(); } catch (e) { toast(e.message); } }

// ===== feed refresh (admin) =====
async function refreshSource() {
  const b = $("refreshBtn"); if (b) { b.classList.add("spinning"); b.disabled = true; }
  try { const r = await api("/api/refresh", { method: "POST" }); toast(r.message); await load(); } catch (e) { toast("Refresh failed: " + e.message); }
  if (b) { b.classList.remove("spinning"); b.disabled = false; }
}

// ===== boot =====
$("sbBid").onclick = () => { sortMode = "bid"; $("sbBid").classList.add("on"); $("sbFit").classList.remove("on"); resetPaging(); render(); };
$("sbFit").onclick = () => { sortMode = "fit"; $("sbFit").classList.add("on"); $("sbBid").classList.remove("on"); resetPaging(); render(); };
$("search").oninput = (e) => { q = e.target.value.trim(); resetPaging(); render(); };
$("fStage").onchange = (e) => { fStage = e.target.value; resetPaging(); render(); };
$("fSector").onchange = (e) => { fSector = e.target.value; resetPaging(); render(); };
$("fMatched").onclick = () => { fMatched = !fMatched; $("fMatched").classList.toggle("on", fMatched); resetPaging(); render(); };
$("fClear").onclick = () => { fStage = fSector = ""; fMatched = false; $("fStage").value = ""; $("fSector").value = ""; $("fMatched").classList.remove("on"); resetPaging(); render(); };

function populateSectors() {
  const sectors = new Set();
  (DATA.opportunities || []).forEach(o => {
    const s = (o.target.sector || "").trim();
    if (s && s.toLowerCase() !== "inferred from filing") s.split(/[,;]/).forEach(x => { const t = x.trim(); if (t) sectors.add(t); });
  });
  const sel = $("fSector"), cur = sel.value;
  sel.innerHTML = `<option value="">All sectors</option>` + [...sectors].sort().map(s => `<option value="${esc(s)}">${esc(s)}</option>`).join("");
  sel.value = cur;
}

function setProv() {
  if (!DATA) return;
  $("provText").innerHTML = DATA.mode === "open"
    ? `This desk scrapes the IBBI register daily, runs the rule-based match against the client book, and tracks each Form G window. <b>Full-access preview</b> — every opportunity and every ranked client match is open to all.`
    : `This desk scrapes the IBBI register daily, runs the rule-based match against the client book, and tracks each Form G window. <b>Opportunity cards are open to all</b>; the ranked client matches with synergy, 29A and reach gates are the premium layer.`;
}
// ===== brand / theme =====
const BRANDS = {
  jarvis: { name: "Jarvis", glyph: "J",
    tagline: "Insolvency opportunity desk — match · Form G tracker · financial snapshot",
    title: "Jarvis — IBC Origination Desk · K C Mehta & Co" },
  kcm: { name: "KCM IBC Finder", glyph: "K",
    tagline: "Distressed-asset origination — match · Form G tracker · financial snapshot",
    title: "KCM IBC Finder · K C Mehta & Co" },
};
function applyBrand() {
  const b = (DATA && DATA.brand) || "kcm";
  const info = BRANDS[b] || BRANDS.kcm;
  document.body.dataset.brand = b;
  $("brandName").textContent = info.name;
  $("glyphLetter").textContent = info.glyph;
  $("tagline").textContent = info.tagline;
  document.title = info.title;
}

// ===== track record (deals) =====
function fmtCr(v) { return "₹" + (Math.round(v * 10) / 10).toLocaleString("en-IN") + " cr"; }
function renderTrackRecord() {
  const tr = DATA.track_record || { deals_closed: 0, value_fmv_inr_cr: 0 };
  const el = $("trackRecord");
  if (!tr.deals_closed) { el.innerHTML = ""; return; }
  el.innerHTML = `<div class="trband">
    <div class="trcard"><div><div class="trk">Mandates Closed</div><div class="trv">${tr.deals_closed}</div><div class="trsub">Acquisition &amp; structuring</div></div></div>
    <div class="trcard gold"><div><div class="trk">Value Created · FMV</div><div class="trv">${fmtCr(tr.value_fmv_inr_cr)}</div><div class="trsub">Benefit enjoyed by clients</div></div></div>
    <div class="trcta"><button class="btn" onclick="openDeals()">${tr.locked ? "🔒 View mandates" : "View mandates"}</button></div>
  </div>`;
}
function openDeals() {
  const tr = DATA.track_record || {};
  const isAdmin = me && me.is_admin;
  $("dealsAdmin").style.display = isAdmin ? "block" : "none";
  const body = $("dealsBody");
  if (tr.locked) {
    body.innerHTML = `<div class="deal-locked"><div class="lkt" style="font-weight:700;color:var(--teal-d);margin-bottom:4px">${tr.deals_closed} closed mandate${tr.deals_closed===1?"":"s"} · ${fmtCr(tr.value_fmv_inr_cr)} value created</div>
      <div class="lks" style="color:var(--muted);font-size:13px">The companies and deal details are a premium view.</div>
      <button class="btn amber" style="margin-top:12px" onclick="closeModal('dealsModal'); ${me ? 'openUpgrade()' : "openAuth('signup')"}">${me ? "Unlock details" : "Sign up to view"}</button></div>`;
  } else if (!tr.deals || !tr.deals.length) {
    body.innerHTML = `<div class="bs" style="color:var(--muted)">No mandates recorded yet.</div>`;
  } else {
    body.innerHTML = tr.deals.map(d => `<div class="deal-row">
      <div><div class="dc">${esc(d.client_name)}${d.target_name ? ` <span style="color:var(--faint)">←</span> ${esc(d.target_name)}` : ""}</div>
        <div class="dt">${esc(d.service_type)}</div>
        <div class="dmeta">${esc(d.closed_on)}${d.notes ? " · " + esc(d.notes) : ""}${isAdmin ? ` · <span class="mini" onclick='editDeal(${d.id})' style="cursor:pointer;text-decoration:underline">edit</span> <span class="mini del" onclick='delDeal(${d.id})' style="cursor:pointer;text-decoration:underline;color:var(--red)">delete</span>` : ""}</div>
      </div>
      <div class="df">${fmtCr(d.fmv_inr_cr)}</div>
    </div>`).join("");
  }
  openModal("dealsModal");
}
let editingDealId = null;
function openDealForm() { editingDealId = null; $("dfTitle").textContent = "Add mandate"; ["dfClient","dfTarget","dfService","dfFmv","dfDate","dfNotes"].forEach(i=>$(i).value=""); $("dfErr").textContent=""; openModal("dealFormModal"); }
function editDeal(id) {
  const d = (DATA.track_record.deals || []).find(x => x.id === id); if (!d) return;
  editingDealId = id; $("dfTitle").textContent = "Edit mandate";
  $("dfClient").value=d.client_name; $("dfTarget").value=d.target_name; $("dfService").value=d.service_type; $("dfFmv").value=d.fmv_inr_cr; $("dfDate").value=d.closed_on; $("dfNotes").value=d.notes;
  openModal("dealFormModal");
}
async function saveDeal() {
  const body = { client_name:$("dfClient").value.trim(), target_name:$("dfTarget").value, service_type:$("dfService").value||"Acquisition & structuring", fmv_inr_cr:parseFloat($("dfFmv").value)||0, closed_on:$("dfDate").value, notes:$("dfNotes").value };
  if (!body.client_name) { $("dfErr").textContent="Client is required."; return; }
  try { if (editingDealId) await api("/api/deals/"+editingDealId,{method:"PUT",body:JSON.stringify(body)}); else await api("/api/deals",{method:"POST",body:JSON.stringify(body)}); closeModal("dealFormModal"); toast("Saved"); await load(); openDeals(); }
  catch(e){ $("dfErr").textContent=e.message; }
}
async function delDeal(id) { if(!confirm("Delete this mandate?"))return; await api("/api/deals/"+id,{method:"DELETE"}); toast("Deleted"); await load(); openDeals(); }

async function load() {
  // Dynamic (FastAPI) first; on a static host (GitHub Pages) fall back to data.json.
  try { DATA = await api("/api/dashboard"); window.STATIC = false; }
  catch (e) { DATA = await (await fetch("data.json", { cache: "no-store" })).json(); window.STATIC = true; }
  applyBrand(); setSrc(); setProv(); renderStats(); renderTrackRecord(); populateSectors(); render(); renderAuth();
}
async function boot() { if (token) await refreshMe(); else renderAuth(); await load(); }
boot();
